services:
  devdb:
    image: postgres:17.2
    user: postgres
    ports:
      - "5432:5432"
    profiles:
      - dev
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - devdb:/var/lib/postgresql/data
      - ./scripts/devdb-init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  devdb:
