services:
  engine:
    build: ./engine/
    ports:
      - "20191:2019"
    volumes:
      - quote-volume:/sqlite
    environment:
      - DBPATH=/sqlite/quotes.db
      - SECRET=${SECRET}
      - PORT=${PORT}
    develop:
      watch:
        - action: rebuild
          path: ./engine
          target: ./engine
  facade:
    build:
      context: ./facade/
      args:
        - NEXT_PUBLIC_SERVER_PATH=SET_THIS_TO_YOUR_API_ENDPOINT_ROOT
    ports:
      - "20190:3000"
    environment:
      - NODE_ENV=production
volumes:
  quote-volume:
