#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER dev WITH PASSWORD 'dev';
    CREATE DATABASE quotes;
    GRANT CONNECT ON DATABASE quotes TO dev;
    \c quotes
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dev;
    GRANT USAGE, CREATE ON SCHEMA public TO dev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO dev;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO dev;
EOSQL
